### ISSUE TITLE
Can't use identifiers from loaded modules

### ISSUE THREAD

**Issue by brandon-leapyear** [haskell-hint/hint#105]
Minimal repro:
1. Write a file `Foo.hs` like
    ```hs
    module Foo where

    x :: Int
    x = 1
    ```
1. Run `stack ghci --package hint`, then in the shell, do:

    ```hs
    import qualified Language.Haskell.Interpreter.Hint
    import Control.Monad.IO.Class
    Hint.runInterpreter $ do { Hint.loadModules ["Foo.hs"]; liftIO . print =<< Hint.getModuleExports "Foo"; Hint.eval "x" }
    ```

The output I see is:
```
[Fun "x"]
Left (WontCompile [GhcError {errMsg = "<interactive>:3:1: error: Variable not in scope: x"}])
```
which shows that `x` was loaded, but evaluating it doesn't work. Same thing happens with other functions like `typeOf`

**Comment by brandon-leapyear** [comment]
Ah I guess I have to do
```hs
loadModules ["Foo.hs"]
setTopLevelModules ["Foo"]
eval "x"
```
is that intended? If so, the docs could clarify what the difference between loadModules and setTopLevelModules intends

**Comment by gelisam** [comment]
I have clarified the behaviour of `loadModules` in the documentation, which will be updated in the next release.

**Comment by gelisam** [comment]
Here is the updated documentation: https://github.com/haskell-hint/hint/pull/160/files#diff-e54c923347aee61efe6f22a52e9d2f061feaf554ef594a2e1a430f7da639306aR190-R193
