### ISSUE TITLE
ghc-9.0.1 support

### ISSUE THREAD

**Issue by gelisam** [haskell-hint/hint#114]
Currently, hint doesn't build with ghc-9.0.1 because a version bounds issue (see #112 for details). Once this gets resolved, let's try building with ghc-9.0.1; if it doesn't build, publish a revision to our own upper bound to reflect that fact, then work on a fix; if it does build, officially add ghc-9.0.1 to the list of supported ghc versions.

**Comment by christiaanb** [comment]
We work around this issue in our CI by adding an `allow-never: *:Cabal` in the `cabal.project.local` file for the cabal-based 9.0.1 builds of Clash: https://github.com/clash-lang/clash-compiler/blob/7a445b03397045bbcdbf42215ed82b233c5d2b54/.ci/cabal.project.local.append-HEAD#L11

Perhaps a similar temporary work-around could be achieved for hint's CI, by adding `allow-newer: True` (https://docs.haskellstack.org/en/stable/yaml_configuration/#allow-newer) to the `stack-9.0.1.yaml`. I can open a PR if this approach is agreeable.

**Comment by gelisam** [comment]
I would prefer to avoid stack's version of `allow-newer`. When building with `allow-newer: true`, we understandably lose reproducibility, because a later build might not use the same version of our dependencies. Unfortunately, `allow-newer` also breaks reproducibility when it is set to false!! More precisely, if I ever build with `allow-newer: true`, then later build without `allow-newer: false` (the default), and my build succeeds, the build might still fail later on or on a different machine. I think the reason is that the build with `allow-newer: true` stores its build artifacts in the same folder as builds with `allow-newer: false`, so if I later accidentally change the configuration in a way which breaks the build, I might not discover it locally because my machine continues to use the build artifacts I previously created with `allow-newer: true`.

Since cabal's approach to reproducibility is different, and its `allow-newer` feature can be scoped down to a single dependency, I am much more willing to try it with cabal than with stack. Don't let the `stack.yaml` files fool you: I use both cabal and stack, and in fact the ghc-9.0.1 build discussed in #112 was using cabal, not stack.

**Comment by gelisam** [comment]
fixed by #117
