### ISSUE TITLE
Use the "Dependabot Preview" app?

### ISSUE THREAD

**Issue by gelisam** [haskell-hint/hint#115]
@KiaraGrouwstra, I have received a request from you to install an app named "Dependabot Preview" to the haskell-hint organization. Can you give me a bit more information?

Most importantly, does Dependabot even support Haskell? https://github.com/dependabot/dependabot-core/issues/2745 makes me think that it does not. Is this a "preview" because you are working on adding Haskell support to Dependabot?

Second, what does the app actually do? When Dependabot for Haskell was discussed on reddit, I listed [several different ways](https://www.reddit.com/r/haskell/comments/ev41o7/comment/fftlc2s) in which such a bot cloud work, and those different ways are appropriate for different workflows.

In particular, my current workflow for hint is that the upper bounds for most of the dependencies are intentionally loose, and I have [a CI trigger which runs once a month](https://github.com/haskell-hint/hint/blob/main/.github/workflows/ci.yml#L12) telling me whether these bounds are too loose; if so, I publish a revision on hackage. The most useful version of a dependency bot for me would thus be a CI trigger which runs when a new version of one of my dependencies is released rather than once month.

**Comment by gelisam** [comment]
Also, why does the app request "write access to code". in addition to "write access to pull requests"? is the github permission system too coarse grained to only give permission to one but not the other?

**Comment by KiaraGrouwstra** [comment]
My apologies! I was pressing random stuff to see what it did unaware this was about the org rather than about my own forks.
I'm checking out how to add a Haskell implementation for it now.
On the permission requests, I've no idea, but that seems like a good question for @dependabot.
Either way, there is no Haskell implementation yet, so there is no point giving any permissions so far.

**Comment by gelisam** [comment]
Thanks for the explanation!
