### ISSUE TITLE
What to do when Hint has trouble finding my modules?

### ISSUE THREAD

**Issue by Qqwy** [haskell-hint/hint#137]
I am using Hint as a way to evaluate something which was passed as a Template Haskell [Name](https://hackage.haskell.org/package/template-haskell-2.17.0.0/docs/Language-Haskell-TH.html#t:Name) at compile-time. This is necessary because in this case, part of the generated datastructure can be precompiled, while part needs can only be created when the app is started.

I have seen some libraries that require the programmer to use their functions as `$(compileMyThing foo 'foo)` where it completely falls on the programmer to ensure that the call is done correctly.

So instead I want to use Hint to do this.
However, I am having trouble with finding the module(s) which are getting compiled. Currently, the code looks something like:

```haskell
{-# LANGUAGE TemplateHaskell -#}
module Example.TH

import qualified Language.Haskell.Interpreter as Hint
import Language.Haskell.TH.Syntax
import Language.Haskell.TH.Lib


-- | Uses Hint's magic to interpret the given `name` at compile-time.
-- (while also being able to splice it into Template Haskell so it can be executed at runtime)
evalParserDefinition :: forall t. Typeable t => Name -> (Either Hint.InterpreterError (ParseRule String t))
evalParserDefinition name =
  System.IO.Unsafe.unsafePerformIO $
  Hint.runInterpreter $ do
  Hint.setImports (["Prelude"] ++ (extractModuleName name))
  Hint.interpret (show name) (Hint.as :: ParseRule String t)
{-# NOINLINE evalParserDefinition #-}

extractModuleName :: Name -> [String]
extractModuleName name =
  case nameModule name of
    Just x -> [x]
    Nothing -> []
```

---

Currently I am testing this code in the same package where this code is also written.
In the future, it will of course be used from another package which uses the library that contains this code.

For some reason, when I started using Hint, it was happily able to find the module name given in a name, like `'ExampleParser.as`.
However, at some point after a few hours, it suddenly no longer was able to, instead giving errors like:

```
    • Exception when trying to run compile-time code:
        WontCompile [GhcError {errMsg = "<no location info>: error:\n    Could not find module \8216ExampleParser\8217\n    Use -v (or `:set -v` in ghci) to see a list of the files searched for."}]
```

I was able to 'hack it to work again' by adding a line `Hint.loadModules ["src/ExampleParser.hs"]` before the `Hint.interpret` statement. However, this seems like a very fragile/error-prone approach, which probably cannot be generalized to reading files once the code is invoked from another project.

So I guess my question is two-fold:

1. Is there a simple reason to tell Hint to just use whatever packages are in scope of the current project where it is being run?
2. If not, what is the proper approach to tackle a situation like this one?

Thank you very much for your help! Hint truly is a very valuable library. :smile:

**Comment by gelisam** [comment]
> Currently I am testing this code in the same package where this code is also written.

That's probably part of the problem, as this is not supported. Try importing a definition from a module which is already compiled, not from your own program.

> Is there a simple reason to tell Hint to just use whatever packages are in scope of the current project where it is being run?

Not yet; you currently have to [find and specify the package database manually](https://github.com/gelisam/hawk/blob/main/src/System/Console/Hawk/PackageDbs.hs#L250-L265) or to set whichever environment variable ghc looks for to find it. I do plan to make this easier in the future, but it's probably never going to be that easy, you'll probably have to specify whether you're building using stack or cabal and point to the correct configuration files so that hint can reproduce the work which those tools perform to tell ghc where to find the packages. At runtime, that information is long gone, we can't just observe at runtime the paths which were used at compile time.

**Comment by Qqwy** [comment]
Thank you for your response. :-)
For now, I've decided to not use Hint for this purpose (i.e. running code from the same package as it was defined in), but instead be more clever with the way the snippets of Template Haskell are being built.
