### ISSUE TITLE
Test ghc-9.4 in CI

### ISSUE THREAD

**Issue by gelisam** [haskell-hint/hint#155]
The GitHub action `haskell/actions/setup` [does not support ghc-9.4.1](https://github.com/haskell/actions/tree/main/setup#version-support) yet, so we'll have to merge #152 without a regression test. This issue exists to remind me to add that regression test once either `stack` or `haskell/actions/setup` supports this version.

**Comment by christiaanb** [comment]
We have GitHub actions support for some of our 9.4.1 upgrades of some of our code. See e.g. https://github.com/clash-lang/ghc-typelits-knownnat/runs/7486517906?check_suite_focus=true

The GitHub actions configuration was mostly autogenerated using: https://github.com/haskell-CI/haskell-ci

I wouldn’t mind setting up something similar as part of #152

**Comment by byorgey** [comment]
Looks like `haskell/actions/setup` now supports GHC 9.4.

**Comment by gelisam** [comment]
Fixed by #152
