### ISSUE TITLE
Compiled hint not working under Raspberry Pi

### ISSUE THREAD

**Issue by yaxu** [haskell-hint/hint#64]
I'm trying to get hint going with an experimental live coding editor for music (https://github.com/yaxu/feedforward), running on a raspberry pi zero computer (running raspbian stretch, with ghc 8.0.1, on an armv6 processor).

It works, but only from `runhaskell`/`ghci`, and not when compiled. Here's what happens when I try to run the example:

```
pi@lcd:~/src/hint/examples $ ./example 
Load SomeModule.hs

Put the Prelude, Data.Map and *SomeModule in scope
Data.Map is qualified as M!

Now we can query the type of an expression
e.g. typeOf M.singleton (f, g, h, 42)
Num t => a -> M.Map ([a1] -> a1, [a2] -> a2, [a3] -> a3, t) a

Observe that f, g and h are defined in SomeModule.hs, but f is not exported. Let's check it...
[Fun "g",Fun "h"]

We can also evaluate an expression; the result will be a string
e.g. eval "length $ concat [[f,g],[h]]"
Illegal instruction
```

As I say, it's fine when run with `runhaskell` or from a `ghci` prompt. I have the same with my hint-driven text editor - it's fine (but of course slow) from runhaskell, but I get an `Illegal instruction` error when interpreting something with hint, via a binary compiled with ghc.

I don't know much about this stuff, but think the problem is probably with the armv6 port of ghc. My efforts in trying to compile a newer ghc for raspbian have not been successful though..

So I thought I'd ask here - any possibility that the problem could be with hint in particular rather than ghc in general? Any pointers much appreciated!

**Comment by mvdan** [comment]
GHC behaving differently depending on whether it's run interactively or statically has popped up before. For example, see #31 and #56, or search this issue tracker for `ghci` or `runghc`.

Have you tried compiling a dynamic binary instead of a static one? I know that's likely not what you want, but I wonder if it would also fail to work properly.

**Comment by mvdan** [comment]
To clarify - the point of a dynamic binary is doing dynamic linking with GHC. I seem to recall a theory in an earlier issue, that went something like "fully static Haskell binaries don't include everything that the full GHC makes available to you via ghci/runghc".

**Comment by yaxu** [comment]
Aha, so building with `ghc --enable-shared` or `cabal install --enable-executable-dynamic might work? I'm traveling away from the pi I was working on but will try this as soon as I get back.. Fingers crossed, thanks!

(I don't need a statically linked binary, and actually thought hint depended on ghc being installed, but from searching the issue tracker as suggested I see this isn't necessarily the case https://github.com/mvdan/hint/issues/3. Pretty excited about the possibility of distributing static TidalCycles/hint binaries without requiring users to install haskell first!)

**Comment by yaxu** [comment]
Ok, wiping `~/.cabal` and `~/.ghc`, running `cabal install --enable-shared hint`, and compiling the example with `ghc --make -dynamic example.hs` produces a binary that works. Hopefully this also works with my own hint-using code. Will close this issue for now. Thanks!

**Comment by yaxu** [comment]
Back on this and despite following my above instructions am getting this from hint: `Failed to lookup symbol: __sync_fetch_and_or_2` - does that mean anything to anyone?

**Comment by yaxu** [comment]
Pardon me, building a binary with `cabal v1-install --enable-shared` didn't work, but building one with `ghc --make -dynamic Main.hs` seems happier..
