### ISSUE TITLE
Request for release of new version in Hackage

### ISSUE THREAD

**Issue by psibi** [haskell-hint/hint#75]
Since `master` already works for GHC 8.6, it is just a matter of releasing a new version in Hackage. Let me know if any help is required if something is blocking the release.

**Comment by mvdan** [comment]
Nothing blocking in particular. Just wanted to wait another week or so, to give the other people active in this project a chance to give any ideas before the release is done.

@gelisam @int-e anything else we should do for 0.9.0?

**Comment by int-e** [comment]
I have checked that `mueval` can be built (and at least at a glance, works) with the current `hint` code and `ghc-8.6.1`. I have no further plans at the moment.

**Comment by mvdan** [comment]
Thanks. I'll post a PR now.

**Comment by int-e** [comment]
Reopening because the actual release isn't done yet.

**Comment by mvdan** [comment]
Done: https://hackage.haskell.org/package/hint-0.9.0

**Comment by psibi** [comment]
Thanks @mvdan !
