### ISSUE TITLE
Deploying hint cross-platform

### ISSUE THREAD

**Issue by yaxu** [haskell-hint/hint#80]
I'd love to deploy haskell binaries making use of hint, to avoid having to ship a haskell interpreter with the whole of haskell.

#3 demonstrates this working under linux, with https://github.com/gelisam/deploy-hint/ from @gelisam as an example, although that isn't up to date.

Are there any other guides / examples towards getting this working? + anything for mac os / windows?

**Comment by gelisam** [comment]
The only reason I targeted linux in that example is because it's easy to create a linux VM which doesn't have ghc on it and then automate a few steps to automatically test that it works. The same approach should work on other platforms.

**Comment by yaxu** [comment]
That's good to know @gelisam, the discussion on #3 shows up some issues around making binaries relocatable though, which I think is more of an issue under mac os / windows. I'd love to see some worked examples on that.

**Comment by yaxu** [comment]
Having deleted my ~/.ghc folder, ghci is happily loading and using the tidal package in haskell-libs (verified with strace).

Still the same error from hint, though.

**Comment by yaxu** [comment]
Seems I just didn't have all the dependencies in place.. getting there

**Comment by yaxu** [comment]
I never got this to work in a satisfactory way. Anyone get hint binary deployment working recently?

**Comment by gelisam** [comment]
But you said it was working in January! Did I change something which broke your solution, or did you mean that you only got part of the solution working? If so, which part works?

**Comment by yaxu** [comment]
It was a while ago now.. I managed to get to the point that it seemed to work on my laptop, but not to get it to successfully transfer on to another system. I then had little idea how to replicate this process on mac os or windows.

**Comment by gelisam** [comment]
I haven't worked on https://github.com/gelisam/deploy-hint/ since I created the prototype, but since I pinned both hint, ghc, and the linux VM to a specific version, the demo should still work, no? I haven't run it in a while...

It sounds like the work you did so far was to update my demo to make it work with a more recent version of hint and ghc? That does sound like a good first step. Do you have a PR for deploy-hint? It would be a shame for all that work to get lost to time!

Like I said last year, the only reason I targeted linux in that example is because it's easy to create and control a linux VM. ~Do you know of a good way to create Windows or MacOS VMs?~ Wait, we do that for a living, I should ask at work 😅

**Comment by yaxu** [comment]
@gelisam I was trying to get this working with tidal, my workings are here: https://github.com/tidalcycles/tidali , I'm not sure how useful they are, though!

**Comment by gelisam** [comment]
I'm glad you found a solution to your problem! Is it a workaround which somehow makes it possible to use tidal without having to deploy hint on a machine which doesn't have ghc installed, or did you find a way to package up the required library files as part of the tidal installation, like in the deploy-hint prototype? If so, do you have some advice for other projects who might want to accomplish the same thing?

**Comment by yaxu** [comment]
@polymorphicengine did the work but yes it follows the principles of the deploy-hint prototype. I believe there are still some problems, e.g. Mac OS big sur and later refuse to run the fake_gcc due to malware protection. I don't think we found a workaround for this.

Other projects could have a look at the github workflow here: https://github.com/polymorphicengine/tidal-gui/
